[workspace]
members = ["simdnbt", "simdnbt-derive", "fuzz"]
resolver = "2"

[profile.release]
lto = true
debug = false

[profile.bench]
lto = true
debug = true

[patch.crates-io]
simd_cesu8 = { git = 'https://github.com/EightFactorial/simd_cesu8' }
